zuul:
  num:  1
isbackup: false
server:
  port: 9010
  tomcat:
    accept-count: 50
    max-threads: 200
    max-connections: 6000
jasypt:
  encryptor:
    password: root
  code: 9aNi3IHj2H6kZr0ODNHtyA==
spring:
  profiles:
    active: pro
  application:
    name: uj
  main:
    allow-bean-definition-overriding: true

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  http:
    converters:
      preferred-json-mapper: gson
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
logging:
  level:
    root: info
    com:
      cj: debug
mybatis-plus:
  mapper-locations: classpath:com/cj/*/mapper/*.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的实体类注册别名
#  type-aliases-package: com.cj
#  # 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
#  type-aliases-super-type: java.lang.Object
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 配置的缓存的全局开关
    cache-enabled: true
    # 延时加载的开关
    lazy-loading-enabled: true
    # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multiple-result-sets-enabled: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100

